@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "com.example.psi_univ.ui.adapters.MapPhotoView#MapPhotoView(Context,AttributeSet)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "com.example.psi_univ.ui.adapters.MapPhotoView",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1322970774 { 
   	label=example
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1648460643 { 
   	label=psi_univ
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1627084567 { 
   	label=MapPhotoView
	labeljust=l
	fillcolor=white
	style=filled
   
   MapPhotoView1170425760XXXMapPhotoView485984503[
	label="+ MapPhotoView()"
	style=filled
	fillcolor=white
	tooltip="MapPhotoView

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_740470037 { 
   	label=Polygon
	labeljust=l
	fillcolor=white
	style=filled
   
   Polygon1627084567XXXisInsidePolygon31627660[
	label="+ isInsidePolygon()"
	style=filled
	fillcolor=white
	tooltip="Polygon

&#10;  @param x the x coordinate of the point the user touched&#10;  @param y the y coordinate of the point the user touched&#10;  @param width the width of the image&#10;  @param height the height of the image&#10;  @return true if the point is inside the polygon, false otherwise&#10; "
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
MapPhotoView1170425760XXXMapPhotoView485984503 -> Polygon1627084567XXXisInsidePolygon31627660;
    
}
@enduml